on:
  push:
    branches:
    - main
 # pull_request:
 #  branches:
 #  - main
 #   schedule:
 # - cron: "0 2 * * 1-5"
 
jobs:
  demo: 
   name: demo-ci avec GITHUB ACITON
   runs-on: windows-latest
   steps :
     - name : HELLO WORD
       run: echo "hello word"
     - run: ls -a
     - name: Recupération du code
       uses: actions/checkout@v3.5.2
     - run: ls -a
 
